image:
  - Visual Studio 2017
  
configuration:
  - Debug
  - Release

platform:
  - x86
  - x64
 
build:
  project: Red.sln
  parallel: true
  verbosity: normal

build_script:
  - ps: |
      Start-Process -FilePath "./Build.bat" -ArgumentList "$env:configuration","$env:platform","HASNUGET" -NoNewWindow
  - ps: |
      if ($env:platform -eq "x86") {
        $Platform = "Win32"
      } else {
        $Platform = "x64"
      }
      
      Get-ChildItem -Path "Build/Test" -Filter *.exe -Recurse -File -Name| ForEach-Object {
        [System.IO.Path]::GetFileNameWithoutExtension($_)
      }
      
      Start-Process -FilePath "Build/Test/$Platform/$env:configuration/Test.exe" -NoNewWindow
