image:
  - Visual Studio 2017
  
configuration:
  - Debug
  - Release

platform:
  - x86
  - x64
 
build:
  project: Red.sln
  parallel: true
  verbosity: normal

build_script:
  - ps:
      Start-Process -FilePath "./Build.bat" -ArgumentList "$env:configuration","$env:platform","HASNUGET" -NoNewWindow
      if ($env:platform -eq "x86") {
        $Platform = "Win32"
      } else {
        $Platform = "x64"
      }
      cd Build/Test/$Platform/$Configuration
      ps: Start-Process -FilePath "Test.exe" -NoNewWindow
