image:
  - Visual Studio 2017
  
branches:
  only:
    - master
  
configuration:
  - Debug
  - Release

platform:
  - x86
  - x64
 
install:
  - nuget.exe restore Red.sln

build:
  project: Red.sln
  parallel: true
  verbosity: normal

# Stalls on "Press any key to continue". Use built-in testing until a proper work around is implemented.
#build_script:
#  - ps: |
#      Start-Process -FilePath "./Build.bat" -ArgumentList "$env:configuration","$env:platform","HASNUGET" -NoNewWindow -Wait

after_build:
- ps: |
    if ($env:platform -eq "x86") {
      $Platform = "Win32"
    } else {
      $Platform = "x64"
    }
    Start-Process -FilePath "Build/Test/$Platform/$env:configuration/Test.exe" -Wait
