language: cpp

compiler:
- clang
- gcc

os:
- windows

before_install:
- echo "Preinstall..."

script:
- echo "Script Started"
- make

after_script:
- echo "Script Ended"

after_failure:
- echo "Failure"

notifications:
  email: false
