language: cpp

dist: trusty
sudo: required

# Don't Build Dev Branches
branches:
  except:
    - /dev_.*/

env:
  global:
    - CODECOV_TOKEN="c57773e7-bd57-474c-be2c-551d66ba421b"

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=gcc
      
    - os: linux
      compiler: clang
      env: COMPILER=clang
      
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: COMPILER=clang

install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    which cmake || brew install cmake
  fi

script:
- bash Build.sh Release x64 coverage
# Run Unit Tests
- ./Build/Test
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" && "${COMPILER}" == "gcc" ]]; then
    # Debugging
    find Build -name "*.gcda"
    find Build -name "*.cpp.gcda"
    find Build -name "*.gcno"
    find Build -name "*.cpp.gcno"
    
    gcov Build/*.cpp.gcda
  fi

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
