language: cpp

compiler:
- msbuild

os:
- windows

before_install:
- echo "Preinstall..."

script:
- echo "Script Started"
- msbuild Red.sln /t:Build /p:Configuration=Release /p:Platform="x64"

after_script:
- echo "Script Ended"

after_failure:
- echo "Failure"

notifications:
  email: false
