language: cpp

dist: trusty
sudo: required

env:
  global:
    - CODECOV_TOKEN="c57773e7-bd57-474c-be2c-551d66ba421b"

matrix:
  include:
    - os: linux
      compiler: gcc
      
    - os: linux
      compiler: clang
      
    - os: osx
      osx_image: xcode8.3
      compiler: clang

install:
- mkdir Build
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    which cmake || brew install cmake
  fi

before_script:
- cd Build

script:
- cmake ../ -G "Unix Makefiles"
- make

notifications:
  email: false
